/*
 * File: leg_spd.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 15-Sep-2025 20:28:02
 */

/* Include Files */
#include "bipedal_wheel_controller/vmc/leg_spd.h"

#include <math.h>

/* Function Definitions */
/*
 * LEG_SPD
 *     SPD = LEG_SPD(DPHI1,DPHI2,PHI1,PHI2)
 *
 * Arguments    : double dphi1
 *                double dphi2
 *                double phi1
 *                double phi2
 *                double spd[2]
 * Return Type  : void
 */
void leg_spd(double dphi1, double dphi2, double phi1, double phi2, double spd[2])
{
  double t29_tmp;
  double t30_tmp;
  double t32;
  double t34;
  double t35;
  double t37;
  double t37_tmp;
  double t5;
  double t9;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     2025-09-15 20:28:02 */
  t5 = phi1 + phi2;
  t9 = cos(t5);
  t5 = sin(t5);
  t29_tmp = cos(phi1) * 0.14 + t9 / 4.0;
  t30_tmp = sin(phi1) * 0.14 + t5 / 4.0;
  t32 = t30_tmp * t30_tmp;
  t34 = t29_tmp * t29_tmp;
  t35 = 1.0 / t34;
  t37_tmp = t32 + t34;
  t37 = 1.0 / t37_tmp;
  spd[0] = dphi2 / sqrt(t37_tmp) * (t9 * t30_tmp / 2.0 - t5 * t29_tmp / 2.0) / 2.0;
  spd[1] =
      -(dphi2 * t34 * t37 * (t9 / 4.0 / t29_tmp + t30_tmp * t35 * (t5 / 4.0)) + dphi1 * t34 * t37 * (t32 * t35 + 1.0));
}

/*
 * File trailer for leg_spd.c
 *
 * [EOF]
 */
