/*
 * File: leg_conv.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 15-Sep-2025 13:09:38
 */

/* Include Files */
#include "bipedal_wheel_controller/vmc/leg_conv.h"

#include <math.h>

/* Function Definitions */
/*
 * LEG_CONV
 *     T = LEG_CONV(F,Tp,PHI1,PHI2)
 *
 * Arguments    : double F
 *                double Tp
 *                double phi1
 *                double phi2
 *                double T[2]
 * Return Type  : void
 */
void leg_conv(double F, double Tp, double phi1, double phi2, double T[2])
{
  Tp = -Tp;
  double t11_tmp;
  double t12_tmp;
  double t21;
  double t23;
  double t30_tmp;
  double t31;
  double t32_tmp;
  double t33;
  double t34;
  double t36_tmp;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     2025-09-15 13:09:38 */
  t33 = phi1 + phi2;
  t11_tmp = cos(t33);
  t12_tmp = sin(t33);
  t21 = t11_tmp * 0.26;
  t23 = t12_tmp * 0.26;
  t30_tmp = t23 + sin(phi1) * 0.218;
  t31 = t30_tmp * t30_tmp;
  t32_tmp = t21 + cos(phi1) * 0.218;
  t33 = t32_tmp * t32_tmp;
  t34 = 1.0 / t33;
  t36_tmp = t31 + t33;
  t33 = Tp * t33 * (1.0 / t36_tmp);
  T[0] = t33 * (t31 * t34 + 1.0);
  T[1] = F * (t12_tmp * t32_tmp * 0.52 - t11_tmp * t30_tmp * 0.52) * -0.5 / sqrt(t36_tmp) +
         t33 * (t21 / t32_tmp + t30_tmp * t34 * t23);
}

/*
 * File trailer for leg_conv.c
 *
 * [EOF]
 */
