/*
 * File: leg_pos.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 15-Sep-2025 20:28:02
 */

/* Include Files */
#include "bipedal_wheel_controller/vmc/leg_pos.h"
#include <math.h>

/* Function Definitions */
/*
 * LEG_POS
 *     POS = LEG_POS(PHI1,PHI2)
 *
 * Arguments    : double phi1
 *                double phi2
 *                double pos[2]
 * Return Type  : void
 */

void leg_pos(double phi1, double phi2, double pos[2])
{
  double a_tmp;
  double t4;
  /*     This function was generated by the Symbolic Math Toolbox version 9.2.
   */
  /*     15-Sep-2025 20:28:02 */
  t4 = phi1 + phi2;
  a_tmp = cos(phi1) * 0.218 + cos(t4) * 0.26;
  t4 = sin(phi1) * 0.218 + sin(t4) * 0.26;
  pos[0] = sqrt(a_tmp * a_tmp + t4 * t4);
  pos[1] = atan2(t4, a_tmp);
}

/*
 * File trailer for leg_pos.c
 *
 * [EOF]
 */
