/*
 * File: leg_conv_fwd.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 15-Sep-2025 20:51:54
 */

/* Include Files */
#include "bipedal_wheel_controller/vmc/leg_conv_fwd.h"

#include <math.h>

/* Function Definitions */
/*
 * LEG_CONV_FWD
 *     T_real = LEG_CONV_FWD(T1,T2,PHI1,PHI2)
 *
 * Arguments    : double T1
 *                double T2
 *                double phi1
 *                double phi2
 *                double T_real[2]
 * Return Type  : void
 */
void leg_conv_fwd(double T1, double T2, double phi1, double phi2, double T_real[2])
{
  double T_real_tmp;
  double b_T_real_tmp;
  double c_T_real_tmp;
  double d_T_real_tmp;
  double e_T_real_tmp;
  double f_T_real_tmp;
  double g_T_real_tmp;
  double h_T_real_tmp;
  double i_T_real_tmp;
  double j_T_real_tmp;
  double k_T_real_tmp;
  double l_T_real_tmp;
  double m_T_real_tmp;
  double n_T_real_tmp;
  double t11_tmp;
  double t19_tmp;
  double t21_tmp;
  double t23_tmp;
  double t25_tmp;
  double t4_tmp;
  double t5_tmp;
  double t7_tmp;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     2025-09-15 20:51:54 */
  t4_tmp = cos(phi1);
  t5_tmp = sin(phi1);
  t7_tmp = phi1 + phi2;
  t11_tmp = cos(t7_tmp);
  t7_tmp = sin(t7_tmp);
  t19_tmp = t4_tmp * t4_tmp;
  t21_tmp = t5_tmp * t5_tmp;
  t23_tmp = t11_tmp * t11_tmp;
  t25_tmp = t7_tmp * t7_tmp;
  T_real_tmp = T2 * 0.0 * 11881.0;
  b_T_real_tmp = T1 * 0.0 * 16900.0;
  c_T_real_tmp = T2 * 0.0 * 16900.0;
  d_T_real_tmp = T1 * t4_tmp;
  e_T_real_tmp = T2 * t4_tmp;
  f_T_real_tmp = T1 * 0.0 * 0.0 * 14170.0;
  g_T_real_tmp = e_T_real_tmp * 0.0;
  h_T_real_tmp = T2 * 0.0 * 0.0 * 28340.0;
  i_T_real_tmp = T1 * t5_tmp;
  j_T_real_tmp = T2 * t5_tmp;
  k_T_real_tmp = T1 * 0.0 * t7_tmp;
  l_T_real_tmp = T2 * 0.0 * t7_tmp;
  m_T_real_tmp = t4_tmp * t11_tmp;
  n_T_real_tmp = t5_tmp * t7_tmp;
  T_real[0] =
      sqrt(((((m_T_real_tmp * 0.11336 + n_T_real_tmp * 0.11336) + t19_tmp * 0.047524) + t21_tmp * 0.047524) +
            t23_tmp * 0.0676) +
           t25_tmp * 0.0676) /
      (t4_tmp * t7_tmp - t11_tmp * t5_tmp) *
      (((((((((((((((((((((((T_real_tmp + T2 * t19_tmp * 11881.0) + T_real_tmp) - b_T_real_tmp) + T2 * t21_tmp * 11881.0) -
                         T1 * t23_tmp * 16900.0) +
                        c_T_real_tmp) -
                       b_T_real_tmp) +
                      T2 * t23_tmp * 16900.0) -
                     T1 * t25_tmp * 16900.0) +
                    c_T_real_tmp) +
                   T2 * t25_tmp * 16900.0) +
                  T2 * 0.0 * t5_tmp * 23762.0) -
                 g_T_real_tmp * 23762.0) -
                f_T_real_tmp) +
               h_T_real_tmp) -
              k_T_real_tmp * 14170.0) -
             d_T_real_tmp * t11_tmp * 14170.0) +
            d_T_real_tmp * 0.0 * 14170.0) +
           T1 * 0.0 * t11_tmp * 14170.0) -
          i_T_real_tmp * 0.0 * 14170.0) +
         l_T_real_tmp * 28340.0) +
        (((((((((((e_T_real_tmp * t11_tmp * 28340.0 - f_T_real_tmp) - g_T_real_tmp * 28340.0) -
                 T2 * 0.0 * t11_tmp * 28340.0) +
                j_T_real_tmp * 0.0 * 28340.0) +
               h_T_real_tmp) -
              i_T_real_tmp * t7_tmp * 14170.0) +
             j_T_real_tmp * t7_tmp * 28340.0) -
            k_T_real_tmp * 33800.0) +
           T1 * t11_tmp * 0.0 * 33800.0) +
          l_T_real_tmp * 33800.0) -
         T2 * t11_tmp * 0.0 * 33800.0)) *
       -17.642907551164431 /
       (((((((((((((t19_tmp * 11881.0 + t21_tmp * 11881.0) + t23_tmp * 16900.0) + t25_tmp * 16900.0) +
                 0.0 * t5_tmp * 23762.0) -
                t4_tmp * 0.0 * 23762.0) +
               0.0 * t7_tmp * 28340.0) +
              m_T_real_tmp * 28340.0) -
             t4_tmp * 0.0 * 28340.0) -
            0.0 * t11_tmp * 28340.0) +
           t5_tmp * 0.0 * 28340.0) +
          n_T_real_tmp * 28340.0) +
         0.0 * t7_tmp * 33800.0) -
        t11_tmp * 0.0 * 33800.0));
  T_real[1] = -T1;
}

/*
 * File trailer for leg_conv_fwd.c
 *
 * [EOF]
 */
