/*
 * File: gen_B.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 08-Aug-2025 17:37:08
 */

/* Include Files */
#include "bipedal_wheel_controller/dynamics/gen_B.h"

/* Function Definitions */
/*
 * gen_B
 *     B = gen_B(Im,Ip,Iw,L,Lm,M,R,l,MP,MW)
 *
 * Arguments    : double Im
 *                double Ip
 *                double Iw
 *                double L
 *                double Lm
 *                double M
 *                double R
 *                double l
 *                double mp
 *                double mw
 *                double B[12]
 * Return Type  : void
 */
void gen_B(double Im, double Ip, double Iw, double L, double Lm, double M, double R, double l, double mp, double mw,
           double B[12])
{
  double b_t41_tmp;
  double d;
  double t10;
  double t10_tmp;
  double t11;
  double t11_tmp;
  double t12;
  double t13;
  double t2;
  double t23;
  double t25;
  double t25_tmp;
  double t26;
  double t26_tmp;
  double t27;
  double t28;
  double t28_tmp;
  double t29;
  double t29_tmp;
  double t3;
  double t4;
  double t41;
  double t41_tmp;
  double t5;
  double t6;
  double t8;
  double t8_tmp;
  double t9;
  /*     This function was generated by the Symbolic Math Toolbox version 9.2.
   */
  /*     08-Aug-2025 17:33:03 */
  t2 = L * L;
  t3 = Lm * Lm;
  t4 = R * R;
  t5 = l * l;
  t6 = Im * Iw;
  t8_tmp = Iw * L;
  t8 = t8_tmp * M * l;
  t9 = Iw * Lm * M * l;
  t10_tmp = Im * M;
  t10 = t10_tmp * t4;
  t11_tmp = Iw * M;
  t11 = t11_tmp * t5;
  t12 = Im * mp * t4;
  t13 = Im * mw * t4;
  t25_tmp = L * M;
  t25 = t25_tmp * l * mw * t4;
  t26_tmp = Lm * M * l;
  t26 = t26_tmp * mp * t4;
  t27 = t26_tmp * mw * t4;
  t28_tmp = M * mp;
  t28 = t28_tmp * t4 * t5;
  t29_tmp = M * mw;
  t29 = t29_tmp * t4 * t5;
  t23 = L * t10;
  t26_tmp = mp * t2;
  t41_tmp = mw * t2;
  b_t41_tmp = L * Lm * M;
  t41 =
      1.0 /
      (((((((((((((((((Ip * t6 + Ip * t11) + t26_tmp * t6) + Ip * t12) + Ip * t13) + b_t41_tmp * t6 * 2.0) + M * t2 * t6) +
                 M * t3 * t6) +
                Ip * t10) +
               t41_tmp * t10) +
              mp * t3 * t10) +
             mw * t3 * t10) +
            t26_tmp * t11) +
           Ip * t28) +
          Ip * t29) +
         t41_tmp * t12) +
        Lm * mw * t23 * 2.0) +
       t41_tmp * t28);
  B[0] = 0.0;
  d = Im * L;
  B[1] = -(t41 * ((((((((((t6 + t10) + t11) + t12) + t13) + t28) + t29) + d * M * R) + Im * Lm * M * R) + d * R * mp) +
                  t25_tmp * R * mp * t5));
  B[2] = 0.0;
  t41_tmp = t10_tmp * R;
  t10_tmp = Ip * M;
  t25_tmp = t10_tmp * R;
  t26_tmp = ((L * t12 + t23) + Lm * t10) + L * t28;
  B[3] = t41 * (((((((t26_tmp + Im * Ip * R) + t41_tmp * t2) + t41_tmp * t3) + t25_tmp * t5) + Im * R * mp * t2) +
                 M * R * mp * t2 * t5) +
                d * Lm * M * R * 2.0);
  B[4] = 0.0;
  d = (((t8 + t9) + t25) + t26) + t27;
  B[5] = -(t41 * ((d - t25_tmp * l) + b_t41_tmp * R * l * mp));
  B[6] = 0.0;
  B[7] = t41 * (((((((((((t6 + t8) + t9) + t10) + t11) + t12) + t13) + t25) + t26) + t27) + t28) + t29);
  B[8] = 0.0;
  B[9] = -(t41 * ((t26_tmp + L * t26) - t10_tmp * l * t4));
  B[10] = 0.0;
  B[11] =
      t41 * (((((((((((((d + Ip * Iw) + t10_tmp * t4) + t11_tmp * t2) + t11_tmp * t3) + Ip * mp * t4) + Iw * mp * t2) +
                   Ip * mw * t4) +
                  t28_tmp * t3 * t4) +
                 t29_tmp * t2 * t4) +
                t29_tmp * t3 * t4) +
               mp * mw * t2 * t4) +
              t8_tmp * Lm * M * 2.0) +
             b_t41_tmp * mw * t4 * 2.0);
}

/*
 * File trailer for gen_B.c
 *
 * [EOF]
 */
