/*
 * File: gen_A.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 08-Aug-2025 17:34:32
 */

/* Include Files */
#include "bipedal_wheel_controller/dynamics/gen_A.h"

#include <string.h>

/* Function Definitions */
/*
 * gen_A
 *     A = gen_A(Im,Ip,Iw,L,Lm,M,R,G,l,MP,MW)
 *
 * Arguments    : double Im
 *                double Ip
 *                double Iw
 *                double L
 *                double Lm
 *                double M
 *                double R
 *                double g
 *                double l
 *                double mp
 *                double mw
 *                double A[36]
 * Return Type  : void
 */
void gen_A(double Im, double Ip, double Iw, double L, double Lm, double M, double R, double g, double l, double mp,
           double mw, double A[36])
{
  double b_t18_tmp;
  double b_t33_tmp;
  double b_t41_tmp;
  double c_t41_tmp;
  double d;
  double d1;
  double d_t41_tmp;
  double e_t41_tmp;
  double f_t41_tmp;
  double g_t41_tmp;
  double h_t41_tmp;
  double i_t41_tmp;
  double j_t41_tmp;
  double k_t41_tmp;
  double t17_tmp;
  double t18_tmp;
  double t2;
  double t23_tmp;
  double t3;
  double t31_tmp;
  double t32_tmp;
  double t33_tmp;
  double t34;
  double t34_tmp;
  double t39_tmp;
  double t39_tmp_tmp;
  double t4;
  double t41;
  double t41_tmp;
  double t5;
  double t6;
  double t7;
  /*     This function was generated by the Symbolic Math Toolbox version 9.2.
   */
  /*     08-Aug-2025 17:33:02 */
  t2 = L * L;
  t3 = Lm * Lm;
  t4 = M * M;
  t5 = R * R;
  t6 = l * l;
  t7 = mp * mp;
  t17_tmp = Iw * M;
  t18_tmp = Iw * L;
  b_t18_tmp = t18_tmp * Lm;
  t23_tmp = Iw * g * l;
  t31_tmp = M * g;
  t32_tmp = L * g;
  t33_tmp = g * l;
  b_t33_tmp = t33_tmp * mw;
  t34_tmp = Lm * g;
  t34 = t34_tmp * mp * t4 * t5 * t6;
  t39_tmp_tmp = L * Lm;
  t39_tmp = t39_tmp_tmp * g * l;
  t41_tmp = Im * Ip;
  b_t41_tmp = Im * Iw;
  c_t41_tmp = b_t41_tmp * M;
  d_t41_tmp = Im * M;
  e_t41_tmp = d_t41_tmp * mw;
  f_t41_tmp = Ip * M;
  g_t41_tmp = b_t41_tmp * L;
  h_t41_tmp = Im * L;
  i_t41_tmp = h_t41_tmp * Lm;
  j_t41_tmp = i_t41_tmp * M;
  k_t41_tmp = Ip * Iw * M;
  t41 =
      1.0 /
      (((((((((((((((((t41_tmp * Iw + k_t41_tmp * t6) + b_t41_tmp * mp * t2) + t41_tmp * mp * t5) + t41_tmp * mw * t5) +
                   g_t41_tmp * Lm * M * 2.0) +
                  c_t41_tmp * t2) +
                 c_t41_tmp * t3) +
                t41_tmp * M * t5) +
               e_t41_tmp * t2 * t5) +
              d_t41_tmp * mp * t3 * t5) +
             e_t41_tmp * t3 * t5) +
            t17_tmp * mp * t2 * t6) +
           f_t41_tmp * mp * t5 * t6) +
          f_t41_tmp * mw * t5 * t6) +
         Im * mp * mw * t2 * t5) +
        j_t41_tmp * mw * t5 * 2.0) +
       M * mp * mw * t2 * t5 * t6);
  A[0] = 0.0;
  d = h_t41_tmp * g;
  c_t41_tmp = h_t41_tmp * M * g;
  e_t41_tmp = Im * Lm;
  h_t41_tmp = e_t41_tmp * M * g;
  d1 = L * M * g;
  t41_tmp = (((t18_tmp * g * t4 * t6 + Iw * Lm * g * t4 * t6) + t32_tmp * mw * t4 * t5 * t6) + t34) +
            t34_tmp * mw * t4 * t5 * t6;
  A[1] = t41 * (((((((((((((((t41_tmp + g_t41_tmp * g * mp) + d * t4 * t5) + d * t5 * t7) + e_t41_tmp * g * t4 * t5) +
                          g_t41_tmp * M * g) +
                         b_t41_tmp * Lm * M * g) +
                        c_t41_tmp * mp * t5 * 2.0) +
                       c_t41_tmp * mw * t5) +
                      t18_tmp * M * g * mp * t6) +
                     h_t41_tmp * mp * t5) +
                    h_t41_tmp * mw * t5) +
                   d * mp * mw * t5) +
                  d1 * t5 * t6 * t7) +
                 t32_tmp * mp * t4 * t5 * t6) +
                d1 * mp * mw * t5 * t6);
  A[2] = 0.0;
  d = Im * g;
  c_t41_tmp = d * t2;
  e_t41_tmp = L * t34;
  A[3] = -(t41 * ((((((((e_t41_tmp + c_t41_tmp * t4 * t5) + d * t3 * t4 * t5) + c_t41_tmp * t5 * t7) +
                      g * mp * t2 * t4 * t5 * t6) +
                     i_t41_tmp * g * t4 * t5 * 2.0) +
                    d_t41_tmp * g * mp * t2 * t5 * 2.0) +
                   t31_tmp * t2 * t5 * t6 * t7) +
                  j_t41_tmp * g * mp * t5 * 2.0));
  A[4] = 0.0;
  d = t39_tmp_tmp * M * g * l;
  c_t41_tmp =
      (((((((t17_tmp * g * l * mp * t2 + b_t18_tmp * g * l * t4 * 2.0) + t23_tmp * t2 * t4) + t23_tmp * t3 * t4) +
          t31_tmp * l * mp * mw * t2 * t5) +
         b_t33_tmp * t2 * t4 * t5) +
        t33_tmp * mp * t3 * t4 * t5) +
       b_t33_tmp * t3 * t4 * t5) +
      t39_tmp * mw * t4 * t5 * 2.0;
  A[5] = t41 * ((((c_t41_tmp + t39_tmp * mp * t4 * t5) + b_t18_tmp * M * g * l * mp) + d * t5 * t7) + d * mp * mw * t5);
  A[6] = 1.0;
  memset(&A[7], 0, 13U * sizeof(double));
  A[20] = 1.0;
  A[21] = 0.0;
  A[22] = 0.0;
  A[23] = 0.0;
  A[24] = 0.0;
  A[25] = t41 * t41_tmp;
  A[26] = 0.0;
  d = Ip * g;
  A[27] = -t41 * (e_t41_tmp - d * t4 * t5 * t6);
  A[28] = 0.0;
  e_t41_tmp = f_t41_tmp * g * l;
  A[29] = t41 * ((((c_t41_tmp + k_t41_tmp * g * l) + d * l * t4 * t5) + e_t41_tmp * mp * t5) + e_t41_tmp * mw * t5);
  A[30] = 0.0;
  A[31] = 0.0;
  A[32] = 0.0;
  A[33] = 0.0;
  A[34] = 1.0;
  A[35] = 0.0;
}

/*
 * File trailer for gen_A.c
 *
 * [EOF]
 */
